name: Deploy to AzureVM
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Deploy to AzureVM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          mkdir -p /home/${{ secrets.USERNAME }}/server
          sudo chmod -R 755 /home/${{ secrets.USERNAME }}/server
          cd /home/${{ secrets.USERNAME }}/server
          sudo rm -rf Client-Server
          git clone https://github.com/BharatSeva/Client-Server.git
          sudo docker rm -f client_server || true
          sudo docker-compose up -d --build

          sudo docker ps --filter "name=nginx" --format "{{.Names}}" | grep -q "^nginx$" && sudo docker exec nginx nginx -s reload || echo "Nginx container is not running, skipping reload."

