global:
  scrape_interval:     5s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'client_server'
    honor_labels: true
    static_configs:
      - targets: ['client_server:3001']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'healthcare_server'
    static_configs:
      - targets: ['healthcare_server:3002']
    # metrics_path: '/metrics'