name: Deploy to AzureVM

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Deploy to AzureVM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          mkdir -p /home/${{ secrets.USERNAME }}/server
          sudo chmod -R 755 /home/${{ secrets.USERNAME }}/server
          
          cd /home/${{ secrets.USERNAME }}/server
          sudo rm -rf Worker
          git clone https://github.com/BharatSeva/Worker.git

          # Give permission to grafana and prometheus
          echo "Changing File Permission for Grafana and Prometheus"
          sudo chmod -R 777 Worker/
          
          sudo docker rm -f worker_service || true
          sudo docker-compose up -d --build
          
          sudo docker ps --filter "name=nginx" --format "{{.Names}}" | grep -q "^nginx$" && sudo docker exec nginx nginx -s reload || echo "Nginx container is not running, skipping reload."
